version: '2'
services:
  ipfs0:
    hostname: ipfs0
    container_name: ipfs0
    ports:
     - 4002:4002
     - 8081:8081
     - 5002:5002
    dns:
     - "8.8.8.8"
    volumes:
     - ./staging/:/export
     - ./data/:/data/ipfs
    image: ipfs/go-ipfs:latest #qnib/ipfs
    privileged: true
